1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000


374it [00:05, 76.68it/s]
reward of episode 0: 0.0




904it [00:13, 73.14it/s]
998it [00:15, 74.57it/s]Traceback (most recent call last):
  File "/Users/ming/Courses/5180/project/dqn-breakout/main.py", line 104, in <module>
    main()
  File "/Users/ming/Courses/5180/project/dqn-breakout/main.py", line 76, in main
    loss = agent.learn()
  File "/Users/ming/Courses/5180/project/dqn-breakout/agent.py", line 90, in learn
    self.save_agent()
  File "/Users/ming/Courses/5180/project/dqn-breakout/agent.py", line 113, in save_agent
    self.model.save_model("training", self.steps)
  File "/Users/ming/Courses/5180/project/dqn-breakout/ConvDQN.py", line 61, in save_model
    path = os.path.join(self.save_dir, f"{type}_{str(steps)}.pt")
NameError: name 'os' is not defined
Traceback (most recent call last):
  File "/Users/ming/Courses/5180/project/dqn-breakout/main.py", line 104, in <module>
    main()
  File "/Users/ming/Courses/5180/project/dqn-breakout/main.py", line 76, in main
    loss = agent.learn()
  File "/Users/ming/Courses/5180/project/dqn-breakout/agent.py", line 90, in learn
    self.save_agent()
  File "/Users/ming/Courses/5180/project/dqn-breakout/agent.py", line 113, in save_agent
    self.model.save_model("training", self.steps)
  File "/Users/ming/Courses/5180/project/dqn-breakout/ConvDQN.py", line 61, in save_model
    path = os.path.join(self.save_dir, f"{type}_{str(steps)}.pt")
NameError: name 'os' is not defined