2it [00:00,  8.40it/s]Traceback (most recent call last):
  File "/Users/ming/Courses/5180/project/dqn-breakout/main.py", line 103, in <module>
    main()
  File "/Users/ming/Courses/5180/project/dqn-breakout/main.py", line 72, in main
    agent.insert_buffer(
  File "/Users/ming/Courses/5180/project/dqn-breakout/agent.py", line 40, in insert_buffer
    self.buffer.add(state, action, reward, next_state, done)
  File "/Users/ming/Courses/5180/project/dqn-breakout/replay_memory.py", line 54, in add
    self.dones[self.idx] = torch.tensor([done], dtype=torch.bool).to(
RuntimeError: destOffset % 4 == 0 INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/Copy.mm":107, please report a bug to PyTorch. Unaligned blit request
Traceback (most recent call last):
  File "/Users/ming/Courses/5180/project/dqn-breakout/main.py", line 103, in <module>
    main()
  File "/Users/ming/Courses/5180/project/dqn-breakout/main.py", line 72, in main
    agent.insert_buffer(
  File "/Users/ming/Courses/5180/project/dqn-breakout/agent.py", line 40, in insert_buffer
    self.buffer.add(state, action, reward, next_state, done)
  File "/Users/ming/Courses/5180/project/dqn-breakout/replay_memory.py", line 54, in add
    self.dones[self.idx] = torch.tensor([done], dtype=torch.bool).to(
RuntimeError: destOffset % 4 == 0 INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/Copy.mm":107, please report a bug to PyTorch. Unaligned blit request